version: '3'

services:
  php:
    image: php:8.3-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8090:80"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pix_user
      MYSQL_DATABASE: pix_database
      MYSQL_USER: pix_user
      MYSQL_PASSWORD: pix_password
    ports:
      - "3309:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8081:80"
